/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 0f092cb09161f98111c9ef299ad91f0a)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	ADMIN_LOGIN_RATE_LIMITER: RateLimit;
	ADMIN_MUTATION_RATE_LIMITER: RateLimit;
	USER_AUTH_RATE_LIMITER: RateLimit;
	USER_ACTION_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	USER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "USER_AUTH_SECRET">> {}
}
