export const categoryMeta = {
  all: { label: "全部地点", shortLabel: "全部", icon: "江", color: "#f4f0e6" },
  landmark: { label: "城市地标", shortLabel: "地标", icon: "楼", color: "#ff7a45" },
  nature: { label: "江湖公园", shortLabel: "自然", icon: "叶", color: "#45c486" },
  culture: { label: "人文艺术", shortLabel: "人文", icon: "文", color: "#9a7cff" },
  neighborhood: { label: "街区漫游", shortLabel: "街区", icon: "巷", color: "#4aa8ff" },
  campus: { label: "高校校园", shortLabel: "高校", icon: "学", color: "#f2c94c" },
  food: { label: "过早宵夜", shortLabel: "美食", icon: "味", color: "#ff5c8a" },
} as const;

export type CategoryId = Exclude<keyof typeof categoryMeta, "all">;
export type CategoryFilter = keyof typeof categoryMeta;

export type Place = {
  id: string;
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  longitude: number;
  latitude: number;
  district: string;
  address: string;
  categoryId: CategoryId;
  featured: boolean;
  imageUrl?: string;
};

export type PlaceStatus = "draft" | "published" | "archived";

export type AdminPlace = Place & {
  status: PlaceStatus;
};

export const seedPlaces: Place[] = [
  {
    id: "yellow-crane-tower",
    slug: "yellow-crane-tower",
    name: "黄鹤楼",
    subtitle: "江城天际线上的千年名楼",
    description: "登楼可以同时看见长江、蛇山与武汉三镇，是理解武汉城市格局最直观的一站。",
    longitude: 114.3064,
    latitude: 30.5444,
    district: "武昌区",
    address: "蛇山西山坡特1号",
    categoryId: "landmark",
    featured: true,
  },
  {
    id: "east-lake",
    slug: "east-lake",
    name: "东湖绿道",
    subtitle: "在城市中心骑进山水之间",
    description: "由湖泊、磨山、森林与城市绿道共同组成，适合骑行、散步和看日落。",
    longitude: 114.3744,
    latitude: 30.5594,
    district: "武昌区",
    address: "沿湖大道",
    categoryId: "nature",
    featured: true,
  },
  {
    id: "hubei-museum",
    slug: "hubei-museum",
    name: "湖北省博物馆",
    subtitle: "从曾侯乙编钟读懂荆楚",
    description: "馆藏以曾侯乙编钟、越王勾践剑等为代表，是武汉最重要的历史文化目的地之一。",
    longitude: 114.3661,
    latitude: 30.5612,
    district: "武昌区",
    address: "东湖路160号",
    categoryId: "culture",
    featured: true,
  },
  {
    id: "wuhan-university",
    slug: "wuhan-university",
    name: "武汉大学",
    subtitle: "珞珈山下的百年校园",
    description: "山、水、建筑与校园生活交织在一起，老斋舍和樱顶构成了极具辨识度的空间。",
    longitude: 114.3652,
    latitude: 30.5373,
    district: "武昌区",
    address: "八一路299号",
    categoryId: "campus",
    featured: true,
  },
  {
    id: "jianghan-road",
    slug: "jianghan-road",
    name: "江汉路",
    subtitle: "从租界建筑走进武汉烟火",
    description: "一条适合步行观察城市建筑、商业变迁和夜生活的老街，也是汉口城市漫游的起点。",
    longitude: 114.2892,
    latitude: 30.5835,
    district: "江汉区",
    address: "江汉路步行街",
    categoryId: "neighborhood",
    featured: true,
  },
  {
    id: "hankou-riverfront",
    slug: "hankou-riverfront",
    name: "汉口江滩",
    subtitle: "长江边的城市客厅",
    description: "从沿江大道走到江滩，可以感受防洪空间、租界建筑群和武汉人的滨江日常。",
    longitude: 114.3072,
    latitude: 30.6033,
    district: "江岸区",
    address: "沿江大道",
    categoryId: "nature",
    featured: false,
  },
  {
    id: "qingchuan-pavilion",
    slug: "qingchuan-pavilion",
    name: "晴川阁",
    subtitle: "隔江望黄鹤的楚地胜景",
    description: "位于龟山脚下，登阁可看长江与武昌岸线，适合串联铁门关和汉阳江滩。",
    longitude: 114.2854,
    latitude: 30.5521,
    district: "汉阳区",
    address: "洗马长街86号",
    categoryId: "landmark",
    featured: false,
  },
  {
    id: "gude-temple",
    slug: "gude-temple",
    name: "古德寺",
    subtitle: "藏在汉口街巷里的异域建筑",
    description: "建筑融合多种风格，空间安静克制，与周边高密度城市肌理形成强烈反差。",
    longitude: 114.3149,
    latitude: 30.6232,
    district: "江岸区",
    address: "工农兵路24号",
    categoryId: "culture",
    featured: true,
  },
  {
    id: "tanhualin",
    slug: "tanhualin",
    name: "昙华林",
    subtitle: "老武昌山坡上的慢街区",
    description: "沿山势展开的街巷保留了多时期建筑，适合从粮道街一路步行到得胜桥。",
    longitude: 114.3145,
    latitude: 30.5535,
    district: "武昌区",
    address: "昙华林",
    categoryId: "neighborhood",
    featured: false,
  },
  {
    id: "lingbo-gate",
    slug: "lingbo-gate",
    name: "凌波门",
    subtitle: "把东湖日出装进取景框",
    description: "武汉大学临东湖的一处标志性亲水空间，清晨与傍晚都有独特的湖面光线。",
    longitude: 114.3745,
    latitude: 30.5355,
    district: "武昌区",
    address: "东湖南路",
    categoryId: "nature",
    featured: true,
  },
  {
    id: "chu-river-han-street",
    slug: "chu-river-han-street",
    name: "楚河汉街",
    subtitle: "沿楚河展开的夜游街区",
    description: "连接沙湖与东湖的城市商业轴线，夜间灯光和滨水步道是主要体验。",
    longitude: 114.3375,
    latitude: 30.557,
    district: "武昌区",
    address: "中北路",
    categoryId: "neighborhood",
    featured: false,
  },
  {
    id: "optics-valley",
    slug: "optics-valley",
    name: "光谷广场",
    subtitle: "武汉最具年轻感的城市节点",
    description: "轨道交通、商业、大学与科技企业在这里汇集，是观察当代武汉活力的一扇窗口。",
    longitude: 114.4011,
    latitude: 30.5066,
    district: "洪山区",
    address: "珞喻路726号",
    categoryId: "landmark",
    featured: false,
  },
  {
    id: "wuhan-tiandi",
    slug: "wuhan-tiandi",
    name: "武汉天地",
    subtitle: "老里份旁的新城市生活",
    description: "从新天地商业街区向周边延伸，可以继续探索汉口历史风貌区和里份生活。",
    longitude: 114.3118,
    latitude: 30.6125,
    district: "江岸区",
    address: "卢沟桥路",
    categoryId: "neighborhood",
    featured: false,
  },
  {
    id: "guiyuan-temple",
    slug: "guiyuan-temple",
    name: "归元禅寺",
    subtitle: "汉阳老城里的清静一隅",
    description: "武汉代表性的佛教寺院，罗汉堂和春节祈福传统构成了独特的地方记忆。",
    longitude: 114.2598,
    latitude: 30.5485,
    district: "汉阳区",
    address: "归元寺路20号",
    categoryId: "culture",
    featured: false,
  },
  {
    id: "shanhaiguan-breakfast",
    slug: "shanhaiguan-breakfast",
    name: "山海关路过早",
    subtitle: "用一条街尝遍武汉清晨",
    description: "烧麦、豆皮、糊汤粉、鸡冠饺集中在街巷两侧，适合清晨边走边吃。",
    longitude: 114.31,
    latitude: 30.6072,
    district: "江岸区",
    address: "山海关路",
    categoryId: "food",
    featured: true,
  },
];
